apiVersion: v1
kind: Secret
metadata:
  name: account-database-secrets
data:
  privileged-database-name: cG9zdGdyZXM=
  privileged-database-username: cG9zdGdyZXM=
  privileged-database-password: ZG9ja2Vy
