---
apiVersion: v1
kind: Service
metadata:
  labels: {{- include "hdp.labels.merge" (dict "commonLabels" .Values.hdp.commonLabels "specificLabels" .Values.hdp.services.labels "context" .) | nindent 4 }}
  annotations: {{- include "hdp.annotations.merge" (dict "commonAnnotations" .Values.hdp.commonAnnotations "specificAnnotations" .Values.hdp.services.annotations "context" .) | nindent 4 }}
  name: {{ include "hdp.headlessService.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: hdpserver-port
      port: {{ .Values.hdp.ports.hdpServer.port }}
      protocol: TCP
      targetPort: {{ .Values.hdp.ports.hdpServer.targetPort }}
    - name: opaccessor-port
      port: {{ .Values.hdp.ports.opAccessor.port }}
      protocol: TCP
      targetPort: {{ .Values.hdp.ports.opAccessor.targetPort }}
    - name: notification-port
      port: {{ .Values.hdp.ports.notificationServer.port }}
      protocol: TCP
      targetPort: {{ .Values.hdp.ports.notificationServer.targetPort }}
    - name: internal-api-port
      port: 8190
      protocol: TCP
      targetPort: 8190
  selector: {{- include "hybriddatapipeline.selectorLabels" . | nindent 4 }}
